spring:
  datasource:
    url: jdbc:h2:mem:credit_app_db
    username: luciano
    password:
  jpa:
    show-sql: true
    hibernate:
      properties:
        hibernate.format_sql: true
#      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html